services:
  products_db:
    image: postgres
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - products_db-data:/var/lib/postgresql/data
      #Copy the init script to the container's entrypoint path
      - ../products_db-init.sql:/docker-entrypoint-initdb.d/db_script.sql
    environment:
      POSTGRES_DB: dan_products_db
      POSTGRES_PASSWORD_FILE: /run/secrets/db-password
      COMPOSE_PROJECT_NAME: DAN
    ports:
      - "8001:5432"  
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

secrets:
  db-password:
    file: ../db-password.txt

volumes:
  products_db-data:

