#Database deployments

# RabbitMQ - Message broker
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-rabbitmq
  labels:
    #app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-rabbitmq
  template:
    metadata:
      labels:
        app: db-rabbitmq
    spec:
      containers:
      - name:  db-rabbitmq
        image: harzen/db_rabbitmq:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 5672
---
# Products (PostgreSQL)

apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-products
  labels:
    #app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-products
  template:
    metadata:
      labels:
        app: db-products
    spec:
      containers:
      - name:  db-products
        image: harzen/db_postgres:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 5432
---

# Users (mySQL)

apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-users
  labels:
    #app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-users
  template:
    metadata:
      labels:
        app: db-users
    spec:
      containers:
      - name:  db-users
        image: harzen/db_mysql:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 3306