#Database deployments

# RabbitMQ - Message broker
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-rabbitmq
  labels:
    #app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-rabbitmq
  template:
    metadata:
      labels:
        app: db-rabbitmq
    spec:
      containers:
      - name:  db-rabbitmq
        image: harzen/db_rabbitmq:v1
        imagePullPolicy: Never
        volumeMounts:
        - mountPath: /var/lib/rabbitmq
          name: db-rabbitmq-storage
        ports:
        - containerPort: 5672
      volumes:
      - name: db-rabbitmq-storage
        persistentVolumeClaim:
          claimName: rabbitmq-storage-claim
---
# Products (PostgreSQL)

apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-products
  labels:
    #app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-products
  template:
    metadata:
      labels:
        app: db-products
    spec:
      containers:
      - name:  db-products
        image: harzen/db_postgres:v1
        securityContext:
          runAsUser: 0
        env:
        - name: PGDATA
          value: /home/postgres/db-data
        imagePullPolicy: Never
        volumeMounts:
        - mountPath: /home/postgres/db-data
          name: db-postgres-storage
        ports:
        - containerPort: 5432
      volumes:
      - name: db-postgres-storage
        persistentVolumeClaim:
          claimName: postgres-storage-claim
---

# Users (mySQL)

apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-users
  labels:
    #app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-users
  template:
    metadata:
      labels:
        app: db-users
    spec:
      containers:
      - name:  db-users
        image: harzen/db_mysql:v1.0.1
        imagePullPolicy: Never
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: db-mysql-storage
        ports:
        - containerPort: 3306
      volumes:
      - name: db-mysql-storage
        persistentVolumeClaim:
          claimName: mysql-storage-claim