#Deployments of microservices

# 1 - frontend
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-frontend
  labels:
    #app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: harzen/ms_frontend:v1
        ports:
        - containerPort: 443
---
# 2 - auth

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-auth
  labels:
    #app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-auth
  template:
    metadata:
      labels:
        app: backend-auth
    spec:
      containers:
      - name: auth
        image: harzen/ms_auth:v1
        ports:
        - containerPort: 8040
---
# 3 - products

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-products
  labels:
    #app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-products
  template:
    metadata:
      labels:
        app: backend-products
    spec:
      containers:
      - name:  products
        image: harzen/ms_products:v1
        ports:
        - containerPort: 8060
---
# 4 - users

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-users
  labels:
    #app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-users
  template:
    metadata:
      labels:
        app: backend-users
    spec:
      containers:
      - name:  users
        image: harzen/ms_users:v1
        ports:
        - containerPort: 8070
---
# 5 - Fake user

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-users-bad
  labels:
    #app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-users
  template:
    metadata:
      labels:
        app: backend-users
    spec:  
      containers:
      - name:  users-bad
        image: buoyantio/bb:v0.0.7
        args:
        - terminus
        - "--h1-server-port=8070"
        - "--percent-failure=100"
        ports:
        - containerPort: 8070
---
# 5 - orders

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-orders
  labels:
    #app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-orders
  template:
    metadata:
      labels:
        app: backend-orders
    spec:
      containers:
      - name:  orders
        image: harzen/ms_orders:v1
        ports:
        - containerPort: 8050
---
# 6 - emails

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-emails
  labels:
    #app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-emails
  template:
    metadata:
      labels:
        app: backend-emails
    spec:
      containers:
      - name:  emails
        image: harzen/ms_emails:v1